export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const CREATE_REQUEST_FAIL = 'CREATE_REQUEST_FAIL';
export const DELETE_REQUEST_ERROR_MESSAGE = 'DELETE_REQUEST_ERROR_MESSAGE';

export const GET_REQUESTS = 'GET_REQUESTS';
export const GET_REQUESTS_FAIL = 'GET_REQUESTS_FAIL';
