export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
export const LOGOUT_USER = 'LOGOUT_USER';
